name: Main

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v1.0.1)'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - "v*" # This enables the CLI trigger

env:
  GODOT_VERSION: 4.6

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Install Godot
        uses: PeterHindes/godot-actions/install-godot@v3.1.1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Open Godot editor for reimport
        run: ${{ steps.install-godot.outputs.godot-executable }} --editor --headless --quit || true

      - name: Build and upload artifacts for all platforms
        uses: PeterHindes/godot-actions/build-godot@v3.1.1
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
          build-dir: ./builds

      - name: Release
        uses: softprops/action-gh-release@v2
        # Run if it's a tag push OR if it was triggered manually
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          # Use the input if it exists, otherwise use the git tag
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: |
            ./builds/windows/windows.zip
            ./builds/linux/linux.zip
            ./builds/macos/macos.dmg
