name: Main

on:
  push:
    branches:
      - main
    # tags:
    #   - v*
    # handled by release below
env:
  GODOT_VERSION: 4.6
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Install Godot
        uses: PeterHindes/godot-actions/install-godot@v3.1.1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
          install-templates: true
        id: install-godot

      - name: Open Godot editor for reimport
        run: ${{ steps.install-godot.outputs.godot-executable }} --editor --headless --quit || true

      - name: Build and upload artifacts for all platforms
        uses: PeterHindes/godot-actions/build-godot@v3.1.1
        with:
          godot-executable: ${{ steps.install-godot.outputs.godot-executable }}
          build-dir: ./builds

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            ./builds/windows/windows.zip
            ./builds/linux/linux.zip
            ./builds/macos/macos.dmg
